---
- name: Install and configure Nginx on webservers
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Change port 80 to 8080 in Nginx config
      replace:
        path: /etc/nginx/nginx.conf
        regexp: 'listen\s+80;'
        replace: 'listen 8080;'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
