---
- name: Install and configure httpd on Ubuntu and Red Hat
  hosts: all
  become: yes  
  tasks:
    - name: Install httpd on Ubuntu
      apt:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install httpd on Red Hat
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Configure httpd on Ubuntu to listen on port 90 
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        line: 'Listen 90'
      when: ansible_facts['os_family'] == 'Debian'

    - name: Configure httpd on RedHat to listen on port 90 
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen 90'
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure httpd on Ubuntu is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure httpd on RedHat is started and enabled 
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'
